# Generated by Django 3.2.8 on 2021-12-01 03:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 12, 1, 3, 32, 43, 260792, tzinfo=utc)),
        ),
    ]
