# Generated by Django 3.2.8 on 2021-12-08 03:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.datetime(2021, 12, 8, 3, 16, 39, 71794, tzinfo=utc)),
        ),
    ]
