# import
from django.test import TestCase


# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# Create your tests here.


class TestHomepage():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_homepage(self):
        # Test name: homepage
        # Step # | name | target | value
        # 1 | open | / |
        self.driver.get("http://127.0.0.1:8000/")
        # 2 | click | linkText=Register |
        self.driver.find_element(By.LINK_TEXT, "Register").click()
        # 3 | click | linkText=Login |
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        # 4 | click | linkText=Register |
        self.driver.find_element(By.LINK_TEXT, "Register").click()
