# Generated by Django 3.2.8 on 2021-12-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, default=39.0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, default=-76.7, max_digits=11)),
                ('name', models.CharField(default='default venue', max_length=30)),
                ('type_info', models.CharField(default='default venue type', max_length=20)),
                ('address', models.CharField(default='default address', max_length=45, unique=True)),
                ('main_sport', models.CharField(choices=[('Basketball', 'Basketball'), ('Soccer', 'Soccer'), ('Tennis', 'Tennis'), ('Baseball', 'Baseball'), ('Other', 'Other')], default='Basketball', max_length=10)),
            ],
        ),
    ]
